### ISSUE TITLE
コンテンツのトピックの決定

### ISSUE THREAD

**Issue by irongineer** [irongineer/learning-git-for-team#5]
## 目的

ターゲットに対して、https://github.com/irongineer/learning-git-for-team/issues/4 で決定した目標を達成するために何のトピックを話すかを決める

**Comment by Nakamura9310** [comment]
# 個人的トピック
今回の勉強会で取り入れるかは別で記載させていただきます。

## 基礎的な概念だけど分かりづらいこと
- ブランチは、コミットを指すポインタ
- HEADは、ブランチを指すポインタ

## 最近業務で調べたこと
- PRを修正する方法
PR作成後に指摘をもらった時の対処法。
PR再作成は必要なく再修正した内容をcommit, pushすればOK(で合ってますか？)。
- 作成後のPRは完全削除できない
closeはできるけれど、完全に削除はできない(という認識で合ってますか？)。
[参考](https://sinsoku.hatenablog.com/entry/2013/10/16/013106)


## まだよく分からないこと
- こまめにリモートへpushするべきか否か
  - メリット
  他のメンバーがリポジトリを見ればどこまで修正されているか分かる。
  - デメリット
  誤ってpushした時の修正が大変? commit --amendやrebaseが制限される?
- rebase -iやsquashでコミットはまとめるべきか
  - メリット
  コミット履歴がきれいになる。
  - デメリット
  細かい履歴が分かりづらくなる？
  (今のところ社保開発では特にまとめなくてよいと言われています)
- どのGUIをどのように使うのがおすすめか
  - 個人的にはCLIで操作しつつVSCodeの拡張機能を用いるのがやりやすいと感じています。

**Comment by irongineer** [comment]
asada さんメモ

Git worktree
https://git-scm.com/docs/git-worktree
https://qiita.com/yoichi22/items/8f92110f24690ca8966f

**Comment by irongineer** [comment]
応用編
Git の内側について知りたい人向け
https://git-scm.com/book/ja/v2/Git%E3%81%AE%E5%86%85%E5%81%B4-Git%E3%81%AE%E5%8F%82%E7%85%A7

**Comment by irongineer** [comment]
### 前提

- ターゲットは Git を多少触ったことある人
  - Git を触ったことない人は対象外（参加してもいいけれど拾わない）

### 学ぶトピック

1. Git の概念
2. チーム開発の流れ
3. Git コマンド（ハンズオン https://learngitbranching.js.org/?locale=ja）
4. チーム開発体験（小さくていいので、PR を出すまでの流れ。その中でコンフリクトの解消など。それをしつつ、コンフリクトの対策など）
5. よくあるトラブルシューティング（逆引きリファレンス）
6. 応用編（Git 構造、Git ツールの使い方など）

これらを各日の予定に当てはめる

**Comment by Nakamura9310** [comment]
## スケジュール

1. Git の概念, チーム開発の流れ (資料には記載し、説明しきれないケースも想定)
2. Git コマンド（ハンズオン [https://learngitbranching.js.org/?locale=ja）](https://learngitbranching.js.org/?locale=ja%EF%BC%89)
3. つづき
4. チーム開発体験
5. よくあるトラブルシューティング（逆引きリファレンス）/ 応用編（Git 構造、Git ツールの使い方など）
